// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg.proto

package com.a.pb.proto;

public final class MsgProbuf {
  private MsgProbuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.x.pb.proto.Msg.MsgHead msghead = 1;
    /**
     * <code>required .com.x.pb.proto.Msg.MsgHead msghead = 1;</code>
     */
    boolean hasMsghead();
    /**
     * <code>required .com.x.pb.proto.Msg.MsgHead msghead = 1;</code>
     */
    com.a.pb.proto.MsgProbuf.Msg.MsgHead getMsghead();
    /**
     * <code>required .com.x.pb.proto.Msg.MsgHead msghead = 1;</code>
     */
    com.a.pb.proto.MsgProbuf.Msg.MsgHeadOrBuilder getMsgheadOrBuilder();

    // required string msgbody = 2;
    /**
     * <code>required string msgbody = 2;</code>
     */
    boolean hasMsgbody();
    /**
     * <code>required string msgbody = 2;</code>
     */
    java.lang.String getMsgbody();
    /**
     * <code>required string msgbody = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgbodyBytes();
  }
  /**
   * Protobuf type {@code com.x.pb.proto.Msg}
   */
  public static final class Msg extends
      com.google.protobuf.GeneratedMessage
      implements MsgOrBuilder {
    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Msg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Msg defaultInstance;
    public static Msg getDefaultInstance() {
      return defaultInstance;
    }

    public Msg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.a.pb.proto.MsgProbuf.Msg.MsgHead.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = msghead_.toBuilder();
              }
              msghead_ = input.readMessage(com.a.pb.proto.MsgProbuf.Msg.MsgHead.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(msghead_);
                msghead_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              msgbody_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.a.pb.proto.MsgProbuf.internal_static_com_x_pb_proto_Msg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.a.pb.proto.MsgProbuf.internal_static_com_x_pb_proto_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.a.pb.proto.MsgProbuf.Msg.class, com.a.pb.proto.MsgProbuf.Msg.Builder.class);
    }

    public static com.google.protobuf.Parser<Msg> PARSER =
        new com.google.protobuf.AbstractParser<Msg>() {
      public Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
      return PARSER;
    }

    public interface MsgHeadOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string command = 1;
      /**
       * <code>required string command = 1;</code>
       */
      boolean hasCommand();
      /**
       * <code>required string command = 1;</code>
       */
      java.lang.String getCommand();
      /**
       * <code>required string command = 1;</code>
       */
      com.google.protobuf.ByteString
          getCommandBytes();

      // required string extras = 2;
      /**
       * <code>required string extras = 2;</code>
       */
      boolean hasExtras();
      /**
       * <code>required string extras = 2;</code>
       */
      java.lang.String getExtras();
      /**
       * <code>required string extras = 2;</code>
       */
      com.google.protobuf.ByteString
          getExtrasBytes();
    }
    /**
     * Protobuf type {@code com.x.pb.proto.Msg.MsgHead}
     */
    public static final class MsgHead extends
        com.google.protobuf.GeneratedMessage
        implements MsgHeadOrBuilder {
      // Use MsgHead.newBuilder() to construct.
      private MsgHead(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private MsgHead(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final MsgHead defaultInstance;
      public static MsgHead getDefaultInstance() {
        return defaultInstance;
      }

      public MsgHead getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private MsgHead(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                command_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                extras_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.a.pb.proto.MsgProbuf.internal_static_com_x_pb_proto_Msg_MsgHead_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.a.pb.proto.MsgProbuf.internal_static_com_x_pb_proto_Msg_MsgHead_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.a.pb.proto.MsgProbuf.Msg.MsgHead.class, com.a.pb.proto.MsgProbuf.Msg.MsgHead.Builder.class);
      }

      public static com.google.protobuf.Parser<MsgHead> PARSER =
          new com.google.protobuf.AbstractParser<MsgHead>() {
        public MsgHead parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new MsgHead(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<MsgHead> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string command = 1;
      public static final int COMMAND_FIELD_NUMBER = 1;
      private java.lang.Object command_;
      /**
       * <code>required string command = 1;</code>
       */
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string command = 1;</code>
       */
      public java.lang.String getCommand() {
        java.lang.Object ref = command_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            command_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string command = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCommandBytes() {
        java.lang.Object ref = command_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          command_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string extras = 2;
      public static final int EXTRAS_FIELD_NUMBER = 2;
      private java.lang.Object extras_;
      /**
       * <code>required string extras = 2;</code>
       */
      public boolean hasExtras() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string extras = 2;</code>
       */
      public java.lang.String getExtras() {
        java.lang.Object ref = extras_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            extras_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string extras = 2;</code>
       */
      public com.google.protobuf.ByteString
          getExtrasBytes() {
        java.lang.Object ref = extras_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          extras_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        command_ = "";
        extras_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasCommand()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasExtras()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getCommandBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getExtrasBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getCommandBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getExtrasBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.a.pb.proto.MsgProbuf.Msg.MsgHead parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.a.pb.proto.MsgProbuf.Msg.MsgHead parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.a.pb.proto.MsgProbuf.Msg.MsgHead parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.a.pb.proto.MsgProbuf.Msg.MsgHead parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.a.pb.proto.MsgProbuf.Msg.MsgHead parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.a.pb.proto.MsgProbuf.Msg.MsgHead parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.a.pb.proto.MsgProbuf.Msg.MsgHead parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.a.pb.proto.MsgProbuf.Msg.MsgHead parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.a.pb.proto.MsgProbuf.Msg.MsgHead parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.a.pb.proto.MsgProbuf.Msg.MsgHead parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.a.pb.proto.MsgProbuf.Msg.MsgHead prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.x.pb.proto.Msg.MsgHead}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.a.pb.proto.MsgProbuf.Msg.MsgHeadOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.a.pb.proto.MsgProbuf.internal_static_com_x_pb_proto_Msg_MsgHead_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.a.pb.proto.MsgProbuf.internal_static_com_x_pb_proto_Msg_MsgHead_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.a.pb.proto.MsgProbuf.Msg.MsgHead.class, com.a.pb.proto.MsgProbuf.Msg.MsgHead.Builder.class);
        }

        // Construct using com.a.pb.proto.MsgProbuf.Msg.MsgHead.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          command_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          extras_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.a.pb.proto.MsgProbuf.internal_static_com_x_pb_proto_Msg_MsgHead_descriptor;
        }

        public com.a.pb.proto.MsgProbuf.Msg.MsgHead getDefaultInstanceForType() {
          return com.a.pb.proto.MsgProbuf.Msg.MsgHead.getDefaultInstance();
        }

        public com.a.pb.proto.MsgProbuf.Msg.MsgHead build() {
          com.a.pb.proto.MsgProbuf.Msg.MsgHead result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.a.pb.proto.MsgProbuf.Msg.MsgHead buildPartial() {
          com.a.pb.proto.MsgProbuf.Msg.MsgHead result = new com.a.pb.proto.MsgProbuf.Msg.MsgHead(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.command_ = command_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.extras_ = extras_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.a.pb.proto.MsgProbuf.Msg.MsgHead) {
            return mergeFrom((com.a.pb.proto.MsgProbuf.Msg.MsgHead)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.a.pb.proto.MsgProbuf.Msg.MsgHead other) {
          if (other == com.a.pb.proto.MsgProbuf.Msg.MsgHead.getDefaultInstance()) return this;
          if (other.hasCommand()) {
            bitField0_ |= 0x00000001;
            command_ = other.command_;
            onChanged();
          }
          if (other.hasExtras()) {
            bitField0_ |= 0x00000002;
            extras_ = other.extras_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasCommand()) {
            
            return false;
          }
          if (!hasExtras()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.a.pb.proto.MsgProbuf.Msg.MsgHead parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.a.pb.proto.MsgProbuf.Msg.MsgHead) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string command = 1;
        private java.lang.Object command_ = "";
        /**
         * <code>required string command = 1;</code>
         */
        public boolean hasCommand() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string command = 1;</code>
         */
        public java.lang.String getCommand() {
          java.lang.Object ref = command_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            command_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string command = 1;</code>
         */
        public com.google.protobuf.ByteString
            getCommandBytes() {
          java.lang.Object ref = command_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            command_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string command = 1;</code>
         */
        public Builder setCommand(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          command_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string command = 1;</code>
         */
        public Builder clearCommand() {
          bitField0_ = (bitField0_ & ~0x00000001);
          command_ = getDefaultInstance().getCommand();
          onChanged();
          return this;
        }
        /**
         * <code>required string command = 1;</code>
         */
        public Builder setCommandBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          command_ = value;
          onChanged();
          return this;
        }

        // required string extras = 2;
        private java.lang.Object extras_ = "";
        /**
         * <code>required string extras = 2;</code>
         */
        public boolean hasExtras() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string extras = 2;</code>
         */
        public java.lang.String getExtras() {
          java.lang.Object ref = extras_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            extras_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string extras = 2;</code>
         */
        public com.google.protobuf.ByteString
            getExtrasBytes() {
          java.lang.Object ref = extras_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            extras_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string extras = 2;</code>
         */
        public Builder setExtras(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          extras_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string extras = 2;</code>
         */
        public Builder clearExtras() {
          bitField0_ = (bitField0_ & ~0x00000002);
          extras_ = getDefaultInstance().getExtras();
          onChanged();
          return this;
        }
        /**
         * <code>required string extras = 2;</code>
         */
        public Builder setExtrasBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          extras_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.x.pb.proto.Msg.MsgHead)
      }

      static {
        defaultInstance = new MsgHead(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.x.pb.proto.Msg.MsgHead)
    }

    public interface elangOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string name = 1;
      /**
       * <code>required string name = 1;</code>
       */
      boolean hasName();
      /**
       * <code>required string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>required string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      // required string age = 2;
      /**
       * <code>required string age = 2;</code>
       */
      boolean hasAge();
      /**
       * <code>required string age = 2;</code>
       */
      java.lang.String getAge();
      /**
       * <code>required string age = 2;</code>
       */
      com.google.protobuf.ByteString
          getAgeBytes();

      // optional string sex = 3;
      /**
       * <code>optional string sex = 3;</code>
       */
      boolean hasSex();
      /**
       * <code>optional string sex = 3;</code>
       */
      java.lang.String getSex();
      /**
       * <code>optional string sex = 3;</code>
       */
      com.google.protobuf.ByteString
          getSexBytes();
    }
    /**
     * Protobuf type {@code com.x.pb.proto.Msg.elang}
     */
    public static final class elang extends
        com.google.protobuf.GeneratedMessage
        implements elangOrBuilder {
      // Use elang.newBuilder() to construct.
      private elang(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private elang(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final elang defaultInstance;
      public static elang getDefaultInstance() {
        return defaultInstance;
      }

      public elang getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private elang(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                name_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                age_ = input.readBytes();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                sex_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.a.pb.proto.MsgProbuf.internal_static_com_x_pb_proto_Msg_elang_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.a.pb.proto.MsgProbuf.internal_static_com_x_pb_proto_Msg_elang_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.a.pb.proto.MsgProbuf.Msg.elang.class, com.a.pb.proto.MsgProbuf.Msg.elang.Builder.class);
      }

      public static com.google.protobuf.Parser<elang> PARSER =
          new com.google.protobuf.AbstractParser<elang>() {
        public elang parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new elang(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<elang> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string name = 1;
      public static final int NAME_FIELD_NUMBER = 1;
      private java.lang.Object name_;
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string age = 2;
      public static final int AGE_FIELD_NUMBER = 2;
      private java.lang.Object age_;
      /**
       * <code>required string age = 2;</code>
       */
      public boolean hasAge() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string age = 2;</code>
       */
      public java.lang.String getAge() {
        java.lang.Object ref = age_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            age_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string age = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAgeBytes() {
        java.lang.Object ref = age_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          age_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string sex = 3;
      public static final int SEX_FIELD_NUMBER = 3;
      private java.lang.Object sex_;
      /**
       * <code>optional string sex = 3;</code>
       */
      public boolean hasSex() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string sex = 3;</code>
       */
      public java.lang.String getSex() {
        java.lang.Object ref = sex_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sex_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string sex = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSexBytes() {
        java.lang.Object ref = sex_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        name_ = "";
        age_ = "";
        sex_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasAge()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getAgeBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getSexBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getAgeBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getSexBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.a.pb.proto.MsgProbuf.Msg.elang parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.a.pb.proto.MsgProbuf.Msg.elang parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.a.pb.proto.MsgProbuf.Msg.elang parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.a.pb.proto.MsgProbuf.Msg.elang parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.a.pb.proto.MsgProbuf.Msg.elang parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.a.pb.proto.MsgProbuf.Msg.elang parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.a.pb.proto.MsgProbuf.Msg.elang parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.a.pb.proto.MsgProbuf.Msg.elang parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.a.pb.proto.MsgProbuf.Msg.elang parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.a.pb.proto.MsgProbuf.Msg.elang parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.a.pb.proto.MsgProbuf.Msg.elang prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.x.pb.proto.Msg.elang}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.a.pb.proto.MsgProbuf.Msg.elangOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.a.pb.proto.MsgProbuf.internal_static_com_x_pb_proto_Msg_elang_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.a.pb.proto.MsgProbuf.internal_static_com_x_pb_proto_Msg_elang_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.a.pb.proto.MsgProbuf.Msg.elang.class, com.a.pb.proto.MsgProbuf.Msg.elang.Builder.class);
        }

        // Construct using com.a.pb.proto.MsgProbuf.Msg.elang.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          age_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          sex_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.a.pb.proto.MsgProbuf.internal_static_com_x_pb_proto_Msg_elang_descriptor;
        }

        public com.a.pb.proto.MsgProbuf.Msg.elang getDefaultInstanceForType() {
          return com.a.pb.proto.MsgProbuf.Msg.elang.getDefaultInstance();
        }

        public com.a.pb.proto.MsgProbuf.Msg.elang build() {
          com.a.pb.proto.MsgProbuf.Msg.elang result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.a.pb.proto.MsgProbuf.Msg.elang buildPartial() {
          com.a.pb.proto.MsgProbuf.Msg.elang result = new com.a.pb.proto.MsgProbuf.Msg.elang(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.age_ = age_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.sex_ = sex_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.a.pb.proto.MsgProbuf.Msg.elang) {
            return mergeFrom((com.a.pb.proto.MsgProbuf.Msg.elang)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.a.pb.proto.MsgProbuf.Msg.elang other) {
          if (other == com.a.pb.proto.MsgProbuf.Msg.elang.getDefaultInstance()) return this;
          if (other.hasName()) {
            bitField0_ |= 0x00000001;
            name_ = other.name_;
            onChanged();
          }
          if (other.hasAge()) {
            bitField0_ |= 0x00000002;
            age_ = other.age_;
            onChanged();
          }
          if (other.hasSex()) {
            bitField0_ |= 0x00000004;
            sex_ = other.sex_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasName()) {
            
            return false;
          }
          if (!hasAge()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.a.pb.proto.MsgProbuf.Msg.elang parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.a.pb.proto.MsgProbuf.Msg.elang) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string name = 1;
        private java.lang.Object name_ = "";
        /**
         * <code>required string name = 1;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }

        // required string age = 2;
        private java.lang.Object age_ = "";
        /**
         * <code>required string age = 2;</code>
         */
        public boolean hasAge() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string age = 2;</code>
         */
        public java.lang.String getAge() {
          java.lang.Object ref = age_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            age_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string age = 2;</code>
         */
        public com.google.protobuf.ByteString
            getAgeBytes() {
          java.lang.Object ref = age_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            age_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string age = 2;</code>
         */
        public Builder setAge(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          age_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string age = 2;</code>
         */
        public Builder clearAge() {
          bitField0_ = (bitField0_ & ~0x00000002);
          age_ = getDefaultInstance().getAge();
          onChanged();
          return this;
        }
        /**
         * <code>required string age = 2;</code>
         */
        public Builder setAgeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          age_ = value;
          onChanged();
          return this;
        }

        // optional string sex = 3;
        private java.lang.Object sex_ = "";
        /**
         * <code>optional string sex = 3;</code>
         */
        public boolean hasSex() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string sex = 3;</code>
         */
        public java.lang.String getSex() {
          java.lang.Object ref = sex_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            sex_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string sex = 3;</code>
         */
        public com.google.protobuf.ByteString
            getSexBytes() {
          java.lang.Object ref = sex_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            sex_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string sex = 3;</code>
         */
        public Builder setSex(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          sex_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string sex = 3;</code>
         */
        public Builder clearSex() {
          bitField0_ = (bitField0_ & ~0x00000004);
          sex_ = getDefaultInstance().getSex();
          onChanged();
          return this;
        }
        /**
         * <code>optional string sex = 3;</code>
         */
        public Builder setSexBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          sex_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.x.pb.proto.Msg.elang)
      }

      static {
        defaultInstance = new elang(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.x.pb.proto.Msg.elang)
    }

    private int bitField0_;
    // required .com.x.pb.proto.Msg.MsgHead msghead = 1;
    public static final int MSGHEAD_FIELD_NUMBER = 1;
    private com.a.pb.proto.MsgProbuf.Msg.MsgHead msghead_;
    /**
     * <code>required .com.x.pb.proto.Msg.MsgHead msghead = 1;</code>
     */
    public boolean hasMsghead() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.x.pb.proto.Msg.MsgHead msghead = 1;</code>
     */
    public com.a.pb.proto.MsgProbuf.Msg.MsgHead getMsghead() {
      return msghead_;
    }
    /**
     * <code>required .com.x.pb.proto.Msg.MsgHead msghead = 1;</code>
     */
    public com.a.pb.proto.MsgProbuf.Msg.MsgHeadOrBuilder getMsgheadOrBuilder() {
      return msghead_;
    }

    // required string msgbody = 2;
    public static final int MSGBODY_FIELD_NUMBER = 2;
    private java.lang.Object msgbody_;
    /**
     * <code>required string msgbody = 2;</code>
     */
    public boolean hasMsgbody() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string msgbody = 2;</code>
     */
    public java.lang.String getMsgbody() {
      java.lang.Object ref = msgbody_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgbody_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msgbody = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgbodyBytes() {
      java.lang.Object ref = msgbody_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgbody_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      msghead_ = com.a.pb.proto.MsgProbuf.Msg.MsgHead.getDefaultInstance();
      msgbody_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMsghead()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgbody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getMsghead().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, msghead_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMsgbodyBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, msghead_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMsgbodyBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.a.pb.proto.MsgProbuf.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.a.pb.proto.MsgProbuf.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.a.pb.proto.MsgProbuf.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.a.pb.proto.MsgProbuf.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.a.pb.proto.MsgProbuf.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.a.pb.proto.MsgProbuf.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.a.pb.proto.MsgProbuf.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.a.pb.proto.MsgProbuf.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.a.pb.proto.MsgProbuf.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.a.pb.proto.MsgProbuf.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.a.pb.proto.MsgProbuf.Msg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.x.pb.proto.Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.a.pb.proto.MsgProbuf.MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.a.pb.proto.MsgProbuf.internal_static_com_x_pb_proto_Msg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.a.pb.proto.MsgProbuf.internal_static_com_x_pb_proto_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.a.pb.proto.MsgProbuf.Msg.class, com.a.pb.proto.MsgProbuf.Msg.Builder.class);
      }

      // Construct using com.a.pb.proto.MsgProbuf.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMsgheadFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (msgheadBuilder_ == null) {
          msghead_ = com.a.pb.proto.MsgProbuf.Msg.MsgHead.getDefaultInstance();
        } else {
          msgheadBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        msgbody_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.a.pb.proto.MsgProbuf.internal_static_com_x_pb_proto_Msg_descriptor;
      }

      public com.a.pb.proto.MsgProbuf.Msg getDefaultInstanceForType() {
        return com.a.pb.proto.MsgProbuf.Msg.getDefaultInstance();
      }

      public com.a.pb.proto.MsgProbuf.Msg build() {
        com.a.pb.proto.MsgProbuf.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.a.pb.proto.MsgProbuf.Msg buildPartial() {
        com.a.pb.proto.MsgProbuf.Msg result = new com.a.pb.proto.MsgProbuf.Msg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (msgheadBuilder_ == null) {
          result.msghead_ = msghead_;
        } else {
          result.msghead_ = msgheadBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msgbody_ = msgbody_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.a.pb.proto.MsgProbuf.Msg) {
          return mergeFrom((com.a.pb.proto.MsgProbuf.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.a.pb.proto.MsgProbuf.Msg other) {
        if (other == com.a.pb.proto.MsgProbuf.Msg.getDefaultInstance()) return this;
        if (other.hasMsghead()) {
          mergeMsghead(other.getMsghead());
        }
        if (other.hasMsgbody()) {
          bitField0_ |= 0x00000002;
          msgbody_ = other.msgbody_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsghead()) {
          
          return false;
        }
        if (!hasMsgbody()) {
          
          return false;
        }
        if (!getMsghead().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.a.pb.proto.MsgProbuf.Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.a.pb.proto.MsgProbuf.Msg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.x.pb.proto.Msg.MsgHead msghead = 1;
      private com.a.pb.proto.MsgProbuf.Msg.MsgHead msghead_ = com.a.pb.proto.MsgProbuf.Msg.MsgHead.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.a.pb.proto.MsgProbuf.Msg.MsgHead, com.a.pb.proto.MsgProbuf.Msg.MsgHead.Builder, com.a.pb.proto.MsgProbuf.Msg.MsgHeadOrBuilder> msgheadBuilder_;
      /**
       * <code>required .com.x.pb.proto.Msg.MsgHead msghead = 1;</code>
       */
      public boolean hasMsghead() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.x.pb.proto.Msg.MsgHead msghead = 1;</code>
       */
      public com.a.pb.proto.MsgProbuf.Msg.MsgHead getMsghead() {
        if (msgheadBuilder_ == null) {
          return msghead_;
        } else {
          return msgheadBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.x.pb.proto.Msg.MsgHead msghead = 1;</code>
       */
      public Builder setMsghead(com.a.pb.proto.MsgProbuf.Msg.MsgHead value) {
        if (msgheadBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msghead_ = value;
          onChanged();
        } else {
          msgheadBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.x.pb.proto.Msg.MsgHead msghead = 1;</code>
       */
      public Builder setMsghead(
          com.a.pb.proto.MsgProbuf.Msg.MsgHead.Builder builderForValue) {
        if (msgheadBuilder_ == null) {
          msghead_ = builderForValue.build();
          onChanged();
        } else {
          msgheadBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.x.pb.proto.Msg.MsgHead msghead = 1;</code>
       */
      public Builder mergeMsghead(com.a.pb.proto.MsgProbuf.Msg.MsgHead value) {
        if (msgheadBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              msghead_ != com.a.pb.proto.MsgProbuf.Msg.MsgHead.getDefaultInstance()) {
            msghead_ =
              com.a.pb.proto.MsgProbuf.Msg.MsgHead.newBuilder(msghead_).mergeFrom(value).buildPartial();
          } else {
            msghead_ = value;
          }
          onChanged();
        } else {
          msgheadBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.x.pb.proto.Msg.MsgHead msghead = 1;</code>
       */
      public Builder clearMsghead() {
        if (msgheadBuilder_ == null) {
          msghead_ = com.a.pb.proto.MsgProbuf.Msg.MsgHead.getDefaultInstance();
          onChanged();
        } else {
          msgheadBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .com.x.pb.proto.Msg.MsgHead msghead = 1;</code>
       */
      public com.a.pb.proto.MsgProbuf.Msg.MsgHead.Builder getMsgheadBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMsgheadFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.x.pb.proto.Msg.MsgHead msghead = 1;</code>
       */
      public com.a.pb.proto.MsgProbuf.Msg.MsgHeadOrBuilder getMsgheadOrBuilder() {
        if (msgheadBuilder_ != null) {
          return msgheadBuilder_.getMessageOrBuilder();
        } else {
          return msghead_;
        }
      }
      /**
       * <code>required .com.x.pb.proto.Msg.MsgHead msghead = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.a.pb.proto.MsgProbuf.Msg.MsgHead, com.a.pb.proto.MsgProbuf.Msg.MsgHead.Builder, com.a.pb.proto.MsgProbuf.Msg.MsgHeadOrBuilder> 
          getMsgheadFieldBuilder() {
        if (msgheadBuilder_ == null) {
          msgheadBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.a.pb.proto.MsgProbuf.Msg.MsgHead, com.a.pb.proto.MsgProbuf.Msg.MsgHead.Builder, com.a.pb.proto.MsgProbuf.Msg.MsgHeadOrBuilder>(
                  msghead_,
                  getParentForChildren(),
                  isClean());
          msghead_ = null;
        }
        return msgheadBuilder_;
      }

      // required string msgbody = 2;
      private java.lang.Object msgbody_ = "";
      /**
       * <code>required string msgbody = 2;</code>
       */
      public boolean hasMsgbody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string msgbody = 2;</code>
       */
      public java.lang.String getMsgbody() {
        java.lang.Object ref = msgbody_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msgbody_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string msgbody = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgbodyBytes() {
        java.lang.Object ref = msgbody_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgbody_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msgbody = 2;</code>
       */
      public Builder setMsgbody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msgbody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msgbody = 2;</code>
       */
      public Builder clearMsgbody() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgbody_ = getDefaultInstance().getMsgbody();
        onChanged();
        return this;
      }
      /**
       * <code>required string msgbody = 2;</code>
       */
      public Builder setMsgbodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msgbody_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.x.pb.proto.Msg)
    }

    static {
      defaultInstance = new Msg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.x.pb.proto.Msg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_x_pb_proto_Msg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_x_pb_proto_Msg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_x_pb_proto_Msg_MsgHead_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_x_pb_proto_Msg_MsgHead_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_x_pb_proto_Msg_elang_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_x_pb_proto_Msg_elang_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tMsg.proto\022\016com.x.pb.proto\"\241\001\n\003Msg\022,\n\007m" +
      "sghead\030\001 \002(\0132\033.com.x.pb.proto.Msg.MsgHea" +
      "d\022\017\n\007msgbody\030\002 \002(\t\032*\n\007MsgHead\022\017\n\007command" +
      "\030\001 \002(\t\022\016\n\006extras\030\002 \002(\t\032/\n\005elang\022\014\n\004name\030" +
      "\001 \002(\t\022\013\n\003age\030\002 \002(\t\022\013\n\003sex\030\003 \001(\tB\033\n\016com.a" +
      ".pb.protoB\tMsgProbuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_x_pb_proto_Msg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_x_pb_proto_Msg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_x_pb_proto_Msg_descriptor,
              new java.lang.String[] { "Msghead", "Msgbody", });
          internal_static_com_x_pb_proto_Msg_MsgHead_descriptor =
            internal_static_com_x_pb_proto_Msg_descriptor.getNestedTypes().get(0);
          internal_static_com_x_pb_proto_Msg_MsgHead_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_x_pb_proto_Msg_MsgHead_descriptor,
              new java.lang.String[] { "Command", "Extras", });
          internal_static_com_x_pb_proto_Msg_elang_descriptor =
            internal_static_com_x_pb_proto_Msg_descriptor.getNestedTypes().get(1);
          internal_static_com_x_pb_proto_Msg_elang_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_x_pb_proto_Msg_elang_descriptor,
              new java.lang.String[] { "Name", "Age", "Sex", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
